### PR TITLE
display local time instead of UTC time

### LINKED ISSUE #63: Execution start time is always in UTC
The execution start time is always in UTC. Was looking in the code and it would be great if we can add support to show the time in current timezone. Its really helpful when you are running builds in multiple windows or trying to figure out when you built the last time.

### PR DESCRIPTION
**Pull request by tHBp**
Updated to display the _local_ time instead of _UTC_ time.
The _timezone_ is appended to the _local_ time as per [discussion here](https://github.com/sindresorhus/time-grunt/issues/63#issuecomment-232412676)

-

 Fixes #63

### CODE REVIEW

**Comment by tHBp** [comment]
Squashed all commits into one @sindresorhus

**Comment by sindresorhus** [comment]
I don't like the new output. It should be in the same format as it currently is, but with a added timezone. So `UTC` would become e.g. `UTC+6`. The best solution would be to added `local: true` option to https://github.com/sindresorhus/date-time that can be used here.

**Comment by tHBp** [comment]
@sindresorhus Haven't gone through the code for ```date-time``` yet. Will do for sure :-)

**Comment by tHBp** [comment]
@sindresorhus Added a local option for ```date-time```. Used that in new commit. Please merge [this pull request](https://github.com/sindresorhus/date-time/pull/3) to make the tests successful for the current PR. Thanks.

**Comment by tHBp** [comment]
Updated the code according to [this PR](https://github.com/sindresorhus/date-time/pull/4). Checks will fail until the [pull request on date-time](https://github.com/sindresorhus/date-time/pull/4) is merged.

**Comment by tHBp** [comment]
@sindresorhus Changes have been made in accordance to `date-time v1.1.0`

**Comment by sindresorhus** [comment]
Thanks. Glad we could finally resolve #63 :)

**Pull request merged**
