### PR TITLE
Add ignored grunt tasks

### PR DESCRIPTION
**Pull request by marlowpayne**
A quick-and-possibly-dirty fix for #51 

Opening for visibility, discussion, and feedback.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I can't really think of any other tasks you'd want to ignore, so would be better to just hardcode watch. Can always expose an option at a later point if there's a need.

**Comment by sindresorhus** [comment]
ping :)

**Comment by marlowpayne** [comment]
Thanks for the input @sindresorhus. Can I ask why would you prefer a hardcode over an exposed optional param? It would extend functionality while maintaining backwards-compatibility.

**Comment by sindresorhus** [comment]
I only add options based on actual needs. We can actually fix it instead of creating more overhead for the developer to consider and learn.

Also don't want to end up like this:

horrible-ui

**Comment by marlowpayne** [comment]
Roger that @sindresorhus, I was just curious. I'll open a new PR with a fix that's hardcoded.

**Pull request closed without merging**
